FROM adoptopenjdk:11-jre-hotspot
WORKDIR /usr/src
COPY target/quarkus-app /usr/src/quarkus-app
CMD java -Xmx64m -jar quarkus-app/quarkus-run.jar

# This file is copied from the "Correlation Student Registration Example" zip file.
# Created by Hubert Baumeister.
# Accessed on 2023-01-11