# This file is copied from the "Correlation Student Registration Example" zip file.
# Created by Hubert Baumeister. 
# Accessed on 2023-01-11

version: '3'
services:
  payment-service:
    image: payment-service
    build: .
 
