version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  facade-service:
    image: facade-service
    container_name: facade-service
    ports:
     - "8080:8080"
    
  account-management-service:
    image: account-management-service
    container_name: account-management-service

  payment-service:
    image: payment-service
    container_name: payment-service

  token-management-service:
    image: token-management-service
    container_name: token-management-service