version: '3'
services:
    
  facade-service:
    image: facade-service
    container_name: facade-service
    ports:
     - "8080:8080"
    
  account-management-service:
    image: account-management-service
    container_name: account-management-service

  payment-service:
    image: payment-service
    container_name: payment-service
