version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  facade-service:
    image: facade-service
    container_name: facade-service
    ports:
     - "8080:8080"
    
  account-management-service:
    image: account-management-service
    container_name: account-management-service

